apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Thomas Homelab
    language: sv
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    hideVersion: true
    quicklaunch:
      searchDescriptions: true
      provider: google
  kubernetes.yaml: |
    mode: cluster
  bookmarks.yaml: ""
  services.yaml: |
    - Kluster:
        - ArgoCD:
            icon: argocd.svg
            href: http://argocd.local
            description: GitOps
        - Headlamp:
            icon: headlamp.svg
            href: http://headlamp.local
            description: Kubernetes Dashboard
        - ingress-nginx:
            icon: nginx.svg
            description: Ingress Controller
        - cert-manager:
            icon: cert-manager.svg
            description: Certifikathantering
    - System:
        - Proxmox:
            icon: proxmox.svg
            href: https://100.87.35.119:8006
            description: Hypervisor
            widget:
              type: proxmox
              url: https://100.87.35.119:8006
              username: root@pam!homepage
              password: 6d0c5412-1273-4b6e-a81a-0237fbcb7919
    - Tjänster:
        - Ghost:
            icon: ghost.svg
            href: https://3145.blog/
            description: Blogg
        - Ghost Admin:
            icon: ghost.svg
            href: https://3145.blog/ghost
            description: Adminpanel
        - Vaultwarden:
            icon: vaultwarden.svg
            href: https://vault.3145.blog/
            description: Lösenordshantering
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - datetime:
        locale: sv
        format:
          dateStyle: long
          timeStyle: short
    - openmeteo:
        label: Väder
        latitude: 59.290527
        longitude: 17.967611
        timezone: Europe/Stockholm
        units: metric
        cache: 5
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
