apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:v02iM5eZ6SxsdnrA0I+T2vAkufZfX3AOdH8jLgP5fno=,iv:bJeHCcaqD4K46YTFmad4VNsCrSiYYfdk63EP/aRofso=,tag:DmZopl5Lt3I08uHTn8nf0w==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:F9zhRrx0OUqCZdEK+4YWTY198bCxcZPWaS12ZBdakU0=,iv:KlvjCg1F/8Q+8rW5s1X4w84PYVmw1rTbRqbdSUwzE6Y=,tag:OxfYceFu8P6KAdHFmSrKbA==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:M67udoDSLKXIiBSqmsPSwdXo7SqfTOpSdlokFved4as=,iv:WKAphENAXNbz21ddu3/Cud9JQGe7fBkUdW3d/A/hJJc=,tag:5u7Oo8PtVjDLE1/nxW+b/Q==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:hHGX23tleYgOLrjLUm7WQQ9T8tgqBBkCzcQ+Z2941Ks=,iv:1vczs7yATfeBseCle8DsukCWPV1mj4jAlDf9+23jZMU=,tag:+mJUywjp2R1htj83CnX8MQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:/co9pmL91GvVrE1yq0H3MV/+i6e2IGM/UGMeFaXoL1I=,iv:Lsxq6pS7PZnjq9OeqLEoyY5i3xl+iomSIvx2yI1mXZo=,tag:brKUedRUPf8Vx8V/1lf5Bw==,type:str]
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:jT5YpD6OILf+lX/JorIGc6c=,iv:OCAxYzzK6WzFjp6QTyGyZNxzDNF3dZpU/w6jrG1aEF8=,tag:6yo98oQ3r0IoSB7SERN4oQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:sVo9EP07TYQQfXAP1dDnJY4WVjTqwXvgumvaSlTm6cJWZa8Y,iv:CRqrFm4l5WmaPkAvHi8JOEFmgoEWJiCmy4gWe1w5zPM=,tag:l3Gwf7DF9uMS2AtT+K4MqA==,type:str]
    HOMEPAGE_VAR_PBS_USER: ENC[AES256_GCM,data:22Qmhq/a5NU51mb0FNMApyw=,iv:7SWwNvCPcvYAnT5cFciSZyir69XtcavloONGPEuYmMk=,tag:F49aD1i9Kq70bcFc/GRMmw==,type:str]
    HOMEPAGE_VAR_PBS_PASSWORD: ENC[AES256_GCM,data:fFHT0LbOyofPIoAfoR3SC4BV8NmDx8F/065AlThr1n3qU3Pc,iv:LA14xB/k2c0UWXpX9QYoL3+5o7YyB/MJXoqO4/Is7i8=,tag:XaYfBWbPM0rQL+FCn0Cb/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTFlVNS9Kc0hKYS9tT0M2
            UlNSMDAzOHgrQnYvTy9TZFdOblVEbTQvZG5rCmRtZ1ZhcktVUTJWU250bU1Va0ti
            dGlSbzlVRzlBeDhieFBBQjhKa1lnYkkKLS0tIEptQkVCMGNISWVKRW4rYzhWRlBm
            cWowTEtjQ1VaWWtpckJsaEdzUndHOFEK5HX6IURVgOWJhPgkYJcoQdXcuMc3vT9N
            nxQmukfXVh8npR06idvoRYONOPeoEVC2/7J677yw/1ka+BR/ZXBJow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T00:24:35Z"
    mac: ENC[AES256_GCM,data:V55dya+/j/FHQWd7YVv+I65BRkt14oZUHNQ++7e/Imt0u+un0U6GVeqDQSxOFIYrafDIcDuuGNlMVFO0C1fWkhAyO9SfF8gYiLFaLHNgNDrKUFtPza/CYr1mncht1xp9LuRB7UeSAYvBYZPcP4a5B7tskNKGFv7pVYZZPKjwW2M=,iv:Qxi+jZu23Nco/BNSt9mbjDWwZsUEXGM3jpQaUuZPgco=,tag:xVLPHOKWlmqWejO54f+9+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
