apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:2tFPCt8uiTDjv3SIeg99gDeMBhfgvf8kqP7KOl9RPww=,iv:vKqRuDLA1z/WK0o47F4I4xHRc/L+wyEryn9ln31FUM4=,tag:/V3tcvMNhqGz8Or5/241/g==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:OwCzpyTfDgFPt/4qMOXCzjVtbxN4tqZwoBhczOFeJr4=,iv:BgT0TE/GS6NTKthGjtveQPdgOl6N5oZ+fAQMy2FM3i0=,tag:G2or+bCxe//maDPiCrFnYw==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:9im1eT+aLVnEGuo6rUJcnCfUvoWBPx5xru5hbWcDd7c=,iv:PkEtH1krjjIeTrcfGcmAgO64Q84k16ETHiDJ+F/+08U=,tag:3NYdyDie8qF23V7CaoPXyQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:d9Yq5St27AHP6ZxV/e2/L71pc4UsU1kpmzc+tr3ZA+s=,iv:4LJX/OmFpVvcsUU10EPGhUMIykXjjYESApL8D4USDXM=,tag:1hdTnQilM1ES6PrP2Qf1ww==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:X7PN4NUkA5YbOGz7TH0IdccbmoPTss3D9hx1WuOaeAk=,iv:wu2TSZPSyJbiKY5pjR7bWQ3NfgAyHA1HPAlKWjuYWK4=,tag:fR8seYTG993LBCMtWViAkg==,type:str]
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:zF4EK/RZU+qPT+WBPqg2+fs=,iv:muVdwD4wvFejoafvYCejmgivJIhx7422g4Vr4qnmS1A=,tag:pAEWnWNhjkD+X3JzBB+kBw==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:w5xn8njSftcF42oe7RNzE2m6M6bFioA2O1npfGXXun+UTeY4,iv:3G8eeJKJPQxeFnoL+m9Ib5EUZE0WtQTJtDkOIpBvKNA=,tag:16Qyhn/F1cxJ6OUxF5Olpg==,type:str]
    HOMEPAGE_VAR_PBS_USER: ENC[AES256_GCM,data:iJvu6n8aNWIAD7fRx3E8ikY=,iv:8f0ZJfYlgZXd1TvibiAhYhj9nYGuffhHqCtF/0nH/ho=,tag:lL43OTvEmw/BIk9tiydx5A==,type:str]
    HOMEPAGE_VAR_PBS_PASSWORD: ENC[AES256_GCM,data:XgqVod4j9GavRSvWySN6wVjQEsaLEwUtDJSuoB7VAczQvpAo,iv:PmYO8XM4qsJmIiOUilqy/+5tVlR94O2toZhglovPxvU=,tag:yTcUUZ2hu7W4tMh7WLRgwg==,type:str]
    HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:mFqhq6A2GqLGfDwT/XSsflq2XvwwE31F+e74H5vUgD8tmFAZ07tzPDj9ZCxcXIiCZnJ/zpnYz94UrkSVSmH7zhSM2oi+nnMFq3gE0D4uq42Mfg9HGW0/NB7Utu4JZeGsvpjlW9qRdSBBtCd7HPolVNPYFKl7007SHWs3bbjEr7BNzeJPo4nzZCSRsEI+JNSCQcsF7EXeQWq5U3kodqMI1ex4368N0hHynLnMTdFsOdjDsQwrMjZKtKZhJzlBlqWwuJk/ZwyK4uxcJF8U1oA/7Di/dpIjwoUd0N+rJVG8EnfoMvQOoFEI5RKO4mk=,iv:dvDAYD6NfxBFHgjcnE9wxn/tn1Jqx2J0Lfoa+L16ubc=,tag:E189qydJJ/7fSCilpYdnUQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:Xk2d/9kMSG8=,iv:wfw7CwXu9bSwvsiCFTUQg25gtTXF1J5mELauKzMnXjI=,tag:LX/ld3svieRAV+ncafALKA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:309gJx8=,iv:TWfwIaQMU0qcZa4Vwe1m4NRdbI04jnQo0qpKHT/mejk=,tag:gAyY/UTeAUQm2EbYScH7Eg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:3+p5OnUpxVStk5G9bw==,iv:z3Lb8XEC594/fxOrfEhD+yeeMSCHnS1ROdtJ1EGk8vc=,tag:Mv42mEb5bN181TYbAdULLQ==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:PfRl01wEeVMOPd2VNM/Uhkash+e/ylqu8vJdCBZsSGQLd3ZdxRolKF5pJV9LiCOZFrYJzp4JVGIEYLs2W62wpKDO6O0=,iv:htfi9yyOnF1FXJmb92mJCegr+ZPANny3KAUGm10zCDk=,tag:VvH5LbnkvcCsiAOu6ag+hg==,type:str]
    HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:eHmbp+A=,iv:aRyEhPUqHk2pMpVOtiVJSCUGz1LhvSuzcsa6ZmnNmQ0=,tag:8Px+BwkyuqBncU4Xf+FD7Q==,type:str]
    HOMEPAGE_VAR_QBIT_PASSWORD: ENC[AES256_GCM,data:qUGxc4WT,iv:NmG/0GjlbpvN8x9bDyncvG2FtY2KSnEg3R9t5wWbPcI=,tag:bwKc9BsPWU9q0NmgmdDgfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWXVDRVRPTC9LZmMrc1V3
            bEdZQllTTGJCNUJHQ0UrZkJJUGtJckVpekFNCjBlRldTWlBkVUhhNllDMXJUZ0Zw
            WGZNQURBekZzNk1wWENMdmt5d0RzTG8KLS0tIHJoR3F6TEp3NnlDTEJoYzhMRXNN
            KzRsU05PSmpQOUpERW9aek1FcUFvRk0KuB7cvxk48MtRP8iWZ9kPryfTQy3HPFSF
            o34ps8m3LP0fehhrYoRiVQKCJWSv2UTrR3iMi26BU2+CAuxnpNUArA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:23:18Z"
    mac: ENC[AES256_GCM,data:yU6eDnmrHgcokzrwRN2t7LF75rXf0sc7Uq1GwTFOdTq/b0t3cRJKp0RmmOe7u0xxcn4WmIUjKS3cehfjQsWOjTRmZKROBBH5b0NIXdQiEERg4lnjbB8T1yFx1H1KAfMCOtvKshZcNzTH/KW5nmmuv4AukFjwkVwLKPzidrg5hUo=,iv:19h+dMJV1gpxEDieC7ubSYJje6htmnbfWlKzp1h9E/w=,tag:yAINOgqMfslnLPcuhfw98g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
