apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:8y8YHpP053/yHs/lPG7KkvSW4GeqPuRG79uaG5G5yNg=,iv:C/QQ8VVStblSfdRzf/7wtPgSudKxNEmJX+owdNiCiwo=,tag:ELsNIjvxvGluJIYBNG9FDw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:qF3cDZcKjNRo8rWdS4+uLG2nmIM320lwJhsD8pkWAXw=,iv:zl60+ikiNbht9Y1evhZLEigT6Vx5urMwfzK43t3Uz+E=,tag:yRz7AnWJg/vw7G0NThUhVg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:ku6pYGQST0J381lALNQwrN84oHusxUdz1aQyGsxVdBc=,iv:FScQN3y3Li8tV3TlC4YVmP5abtxOc2MwQgKV4ZR+jXU=,tag:OU/mU7neZ3oflP7KhtKTvQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:XxmRrToSP1vHJ3xkQAasYhcBQx2jOVfTwSXJlJDpwVY=,iv:sJquvKCVd1RgdkvH6kxZb7HfnsVpmd8xw9GFQgl9dk4=,tag:JpHDGgIdWZOI/djoeIe4+A==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:KSK0/X+ftA3tw7x/mNjMFmdtAG28YioNR0vo/C3kANg=,iv:a1d4ifwP/W/JoGskf5d7yE066SoqhPa0dekLQCFoJ2c=,tag:AP3w9TMTglZO1IOYKxYlcA==,type:str]
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:0wimQGKFbFeCpWdtMKz6Fdk=,iv:v+1/xRxJt+mXm9nloeHZHvz9T2VONSwV+1kjgCIeAX4=,tag:NsuhGVPV4mz+0+PCcDeskQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:L4L5VxzQO2d2gUIg/JL4iyOT36k1DjWLxQSSgp+susTUtFdH,iv:91KICf2g5lArRzml38QlTm7hbIe3IzxykJJCeiNKOdQ=,tag:zb9tc7Oiwv81SSgFlUsJow==,type:str]
    HOMEPAGE_VAR_PBS_USER: ENC[AES256_GCM,data:eb5r+abULuRzVdlyDFCuDDw=,iv:Q0npws465WsiPMc9NCw9f0QF5eaTE+15ZZN5ekLxijU=,tag:9fjZjOqXTalr9nxnbR9+rQ==,type:str]
    HOMEPAGE_VAR_PBS_PASSWORD: ENC[AES256_GCM,data:c6IIOpXGMkT17VG2WnTJdc6+JCI4fVOC1k/h2ykl0Omun7aZ,iv:IIy5BRXJ5H/7tIMk0UVAbRwwnDGzFbfHZJudZBRePbw=,tag:IFGVMrB8jnOMXgJM78NhwA==,type:str]
    HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:RkbddpLCNF+osU6kwIOYmtbyojUGjM5deb6PttKpPcCHXo3Gof0YmgtBUp/v0rCN0QvOGSP1pRHTtJojgLKrSJa68VBi2bU47fnCxQQgSpG7f9BOFdq5HgvZtMCaEgFh6SnFbA2X/o4uCAyUmbAAT7GKDAJNhd29/a1jbvWrZkqMh/b62b4LstWlralQu1CsuH9tjKL/jaiJyL2wnsuac8BM84dbiqzpYGOzjT4B19fBcfFziKcO/p8DITYzbf0tfbVdz2U+QCZJZXipqbQAnzd58S2i9zPVQHYDIZB7HyomU9//GIdLsYPH3mQ=,iv:9IfpQaKWV5PyXcqBWDa6/x97EPE1rg33PCqUZfLHfI4=,tag:qyHjTuo/NpOjQ3Ka7SOqgA==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:mfy5sPyWXe8=,iv:XyIQAX1kOmkps5om4crdO4w/ggDzYEogdwB69+xQeLI=,tag:3zwKiYDUE5k9MNL4hr42fA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:A7iDR7M=,iv:5ohvK06M8l15v12HaG2UJv0DbV3xuXLnsWQuwpfkXjY=,tag:rVwPF+YKoMZtGOvn9kvwEA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:EuQSG+Ml,iv:IQddA38ymFR1dDmWaDB/5XK/fPGeyomSQvAU8JCLoCI=,tag:U4/8wEkhSoDmAjA7bMgmLA==,type:int]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:sFLn70p3egzfD73Pg4N9WfzAwgQN/Q+Ax0eG3OS00cbHAoTt7I0MfP/1TuUihftg9XbzJE6kMjDziaHu5w+2PHh7s7I=,iv:jAhpWmJSCwxF/0Ir7ollyRQ0bnlsVJRo3AWLElge6sc=,tag:fcji8j9jh8NcqNXOIYgetg==,type:str]
    HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:9JyVXzs=,iv:sltG67LVfa95Sks3xE5VuU/RTn5oEcdMlYsg/CEMkaw=,tag:U9QiIO3eJF7wOnV/ncW92Q==,type:str]
    HOMEPAGE_VAR_QBIT_PASSWORD: ENC[AES256_GCM,data:IicEHezz,iv:P6vMkPKVq2pdDkNzm9Eli267dBMnPI3M+xkMo8Su5nw=,tag:60jn/rHjzKuoU4Na51v/Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZHFXeFo0S3FsMzhwVUFG
            TS9TeWZndEdjNVMwTzVWY1JTeHAweUZQUlNFCjJpOE91bFpJS2V4UVIwSVMyU3dY
            Sy9DQ2Y2dTBZbG94dm5rdFd1MVhvOGsKLS0tIDBLSXpjbEZhK0tHeUx2eDhlM3cz
            R2JxSXJHR25HaEY1aGdLaTdQdlBmeTQKSxkMiL7g0kMqFE6A6v45yRUfuwGQIIzC
            IXrb+Xx9X014xWUWz1scd4mizHXgEkjW1nPBpyGBjcEWv884a45Hyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T17:06:28Z"
    mac: ENC[AES256_GCM,data:IbHiTay7I1tv2glk0stw3HcvuJ2v9DcRRIFtR/jTir8VPsxPyHttsuLEGfvuzXPyTxAN8ou4nGy2NKiQwYIy1LbgTFFdsOhJ+FGZ4WPOyH556tU4KTS9cLQquTaJ0+AW/NN+TguIqxx5nyEbFO2y4PL9n6aqX3x9FFWPKhbx2es=,iv:+3FCEO7R2QEmybLIfUoAFJ8t1syt6LpgBBNa5cwkewc=,tag:lB7mD0jL3TPmRvMC7Jhaaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
