apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:XzJ9bOp21fxq+6RpyjMVe0ms25/fiRsCyCrv2EeN+GyFTlmOQzpVa+E3TSh4AxPBaPSobE9ePOYuZCAkxovXdQ==,iv:f+/c472O1wckz7OHBdrxB9dI0+fYoDkomfOoZBSSSXk=,tag:am36PcsfXLvT6SH2Zez/nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVS8yNGV2VWdDc3BZUGsw
            aDQvSXdDek1CTjdVaUEydnJKVmJqRmZaOUJzCkZqUG9GUDV4VTMvMHNlQXFobGdM
            SmhaVis2b0lqdkU4WlE2Zm1HWTFEZkEKLS0tIEJjRktXWmF5ZExJOFJ2Y014MEk2
            VUc4TmxOTHhjaXI3STRVZTEwVWN0SkUKnBu25L2ybD6uauAmZmtC2F1JA7ZEQH54
            4INR7V8tGn3DDMNFUYr/hzkMFzaW0eL0Rn7eFMb6Gq0BXC1T0AHL9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T15:03:13Z"
    mac: ENC[AES256_GCM,data:bjWwP76IagXztmzUIwsNKHAXQLUlBDDOpe+aTgtjsmDALI7nTHKMXzMMpimD6wy+Zo97Jz/73yX9EAcOqHFKrrRRFDp8lw/NAXmbId26LEW+lfi+wJ5BSoDzv+TDNK708cG2tHLt3v2AYdIHpbOhT7rsifmxF4CSZ+T/TMKo0eA=,iv:15NyEeUlWDcqpeApP21ArjMr8ejFZUZRbOuiIu7ONkQ=,tag:/Ppwo8wA+c0xIblnDMCHnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
