apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Thomas-3145/homelab.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/pdb
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
