apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 8.*
    helm:
      releaseName: velero
      valuesObject:
        credentials:
          useSecret: true
          existingSecret: velero-credentials
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: homelab-backups
              default: true
              config:
                region: auto
                s3ForcePathStyle: "true"
                s3Url: https://46f834d31a5157b819ff9c879ee07851.r2.cloudflarestorage.com
          volumeSnapshotLocation:
            - name: default
              provider: csi
          features: EnableCSI
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.11.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        upgradeCRDs: false
        snapshotsEnabled: true
        kubectl:
          image:
            repository: docker.io/rancher/kubectl
            tag: "v1.32.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
