apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:6QkI2XKON376ltX5sJVEocevdadLO74VCcu9YLKmQzsKHytEIgFWjdYDpovOmFSTWV9+FXYIbEjgwlBmL3rTqZbyQrr+3IK5ECdLTVUABjf9zhJ1WhPb57lXtbzRDKJ5RFXLiIJG9Ozr29kA+W4HOrwFHxp+N/yek3D4gTIwxGT0aTzOFN4NO86XX8iIAw==,iv:vzpLOfvZXGekn2GMekKlegdxjCBG9gaEffHGuFpqtgU=,tag:IEBT8tXrcbvIw1wv7IKzrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWlMwTk4yWkZMVE4vQjB1
            cWFObE1rcTlxUnpraGFIa0lIbmdNUnJEUVZnCkJkcVZ0YVhGeERNcFhTWkNtMkIv
            QXl0UDlQYjQwczF4Z3Z3L2FWb1A4MXMKLS0tIFFtK1Q0cXkrV2ZmS2pTNTlSVFVP
            aHR6dWlRWWthVytlbVNlTTlhaWNVdDAKMwV9eL5aEdqvpf1HzEo9QvNHJOoB/IEF
            FQk+/2g/Sh3PalnUQlxlXTyr5p88Ubk/C4iB4qS70TMVzH3G+EGHLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:54:35Z"
    mac: ENC[AES256_GCM,data:5bwRhRrjk7r3+eHuAhWYG3J5JOcUEIEfZwetRjCoC0iScx/Xq0SHBIIbhE6OvV8oJHvttAmQkXdqKqDc1aTqJ3a+5+l6WxAQoOuh10ukYKGtQFow6dpXfIz5G4xSngpwmDwjT7sm+3dgimMXi8gar2vnacG3IDrt0EkpBoc79yo=,iv:4baj9LEV2mBlOANWOTKHdmL7KR369EhjQloxdQrP61c=,tag:X0Ew5uw/KpZE+UDDBNk2bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
