apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:fc1KPY/pjyQjtJVCoBVoQ+gOru9HnMJYyIrZt0DuSX4ZHAzfAksH9iFJSY2TStgpvnJmeR/MQOzPZhnOHucTJUxAex7J+RjYGT+sZrKGBBO/Qr8Zdk+O4dC65JeetAxXgeezJntogCl9ZUsyCWF/ZHIb/mUmjcDgUW0VQcgSF08cq7KEy6gFrBt4FqSZeQ==,iv:GssekAezGhLGdiFM1IevEySTt2RldDrEhpPDAp9Ta5k=,tag:rKzDR3qPlSSHL7fc/gxcHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUG1tcGxadC9VbmpzQTVQ
            MFhQM0liSW9GV0ZldGIzVDIrSXhMWkRwVkgwCjhTRnBQYUVEK2F4dFlmd1JYVlp2
            RGhZcHVtbUtJb0t2VGNrbjhNSXBnQ28KLS0tIGhGWlFFYnMwdjh5YUhOc29iYTd3
            dVV1U2Raa3Q4eWNkQnltdTU5cFZ6ZEEKlRKMQO1p74TVdOFEgHhW50iRNFkc9DAV
            xw+/kNpp3zNgKjEUfSMQhc1HNIM4CALpL6VNwFhYuj+qCt8bM3BFLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:09:23Z"
    mac: ENC[AES256_GCM,data:iFsydA4bLkZv4enpZS7M8U5kd/RN+QftqxyOJqcMHYxhycswbKErs/OE+ziE4vWEFlvNqNbcFNqfWwrmeA/ebAtq5217DuwxCo9T8Lf02cAanA3UQnNMqRBpfVALwJppyoSwTNr7ngsKRIOOpOeVH3KgxJ35d1CB7l3d1NGSPIk=,iv:BYGeyH5ISmDffRDYetZGCVfS3mQPijaYA94IxvH+zks=,tag:5XGIc1Y8pGju+uFUbDCVuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
