apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:Jnr7eA+QXZe7r58WOLLKTMiKfsVd2LAQARrG0o2O2YsU3GT6SbAlpSoJ9GgKBn7vbFpgdShCV0vdt1EUpO6guQHPfa+Bhyd0xwBXR7+omkgM8cRycqS5qkWg63uMZefinUw9lSlk6SZUJDO9msSHASm56+zf4N4vgeYRKOrKMkiMfv4d6NMeO7+VCVieXw==,iv:YUUMSfJgWTdMSCVIpee5Fw1BpfyJ01eIgvY0WGjulDY=,tag:Bboot4AtUWqnfjUAFWDOow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS2psVEVyNWhZYkk5c0lG
            Qlp0czFuRjVac2poUDdvSG1IK1dKaEdkYlFzCkV2V3k0d0hsMG1YUmFDcitzS0JS
            TE4wcFZnTGxQb25jVmFDMlJMRlUvYUkKLS0tIDhqejZJdVBuRDR2UFlqR0NoUFla
            RFh4SXExdDR1TUVhV2IzckVLdmMyNEUKY+wXTSyW3tNEcEjTkDa+VuT1ZxsgqjKT
            F4YBfcJ2BGt9cDmJSLDdjsOwDtiFkg3YIkVhanXevLPK2upBn8E6TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T17:55:00Z"
    mac: ENC[AES256_GCM,data:tbF2o5HF5/wGm+Sv0D6fJedA9OBXFbProctRFm2DlVH7MZS8EyrGY/Agb/s76qGKspRVcfY0ErZTEVPgUgK455QwafSaVDvjavRpMo32B6TgzsXz7qdQFaXUCpPDxiS+ojGf6EYh1erajHiVr9ymefWNs8Q3cTbumDZpaGSdg7o=,iv:k+H3tZ7X1cAw+L4yZ7gpxC4tGMtYLrhSX6v91fAooCU=,tag:nLEMEkjURqkMKzrIPg0NUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
