apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:WG5eeQkU1BcG7E52bY31O2nuImCeL2Glpi/+UVj5TEZaxHT82l4D8bJZ8WlGHsEoGqt36l10uG3mnWt4Dy/dcg==,iv:xSEWJroc5Go8WroV/FoFOcdSmvqWWJ67qDAWl7i5Gv8=,tag:HDAkTtVIpkohKb8Bi0STXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdVhRaE56aUNvNlltZUNV
            YlJxOUppZzhmRGR3MlVCU1pJcVN6UkVlVGtnCmVBM0E1WjVrc1FkNFJPem1JL2tG
            Q2lwTmtTMzBpa1JpOFhRemt0VzAveGsKLS0tIERLTlU0YWEraStwTittVFJiWW45
            U0VvS2JiVUFuc01BeUlDcE1mVkxNQXMKstb/aEZrF5KynglEr3BOzdRN/C5rs6m7
            pqi3r2+XMpZkwAIWCgrbR0PVLR8ucGB2ZD6B/Fmus2pQGR28MKh/Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T18:58:04Z"
    mac: ENC[AES256_GCM,data:amig1fxQyUWv7ipA8unPjitnXBMCCingEx+nDwHX7OR//zguk0wz53DEpXU2QUjpLt5MWXnQyTwKsAUDO3Ayjgh07eU1PQqYNyPQztPjsEX3MGQC7ptSjXPPs4DnXuK0/Grw8BIGkP4Hj6mQ0s3qvy8AnlVG9HLUc9j2DFTR2QE=,iv:6YsioaEwCisDM8Jo660stg+KKtPFL614UVqGQ9GfOps=,tag:f2E2Lusitm3r9L3zSqFp1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
