---
- name: Install Docker
  ansible.builtin.import_tasks: docker.yaml

- name: Deploy compose stack
  ansible.builtin.import_tasks: compose.yaml

- name: Install study pipeline
  ansible.builtin.import_tasks: pipeline.yaml
