apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:9aYZ94olX3HrW58hk9S47yRKJCdURpHGYMTRfsgZGpxcjUGCdDvv0HTNAWypP5Pj,iv:brk0PJIVfP6/p54SuLyzaRMjuw8DJMWDT2Xq18tpmKo=,tag:mK2kP82Db3hsRkheBvfZ6g==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:9dSzMse3ElXqFV1hwaKtKoSI0Ydy5PkGhW/dHMtFCB4+nAksH4+qa+lx2y7D7NNW,iv:m0fUTZqXKwnculN77m/L2moX3SJrRnuAOHwhFPuWgAw=,tag:tWNL9FCzl/40XaK5l8Hf6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NFVkaTdtSVVBSWtFS0tz
            RzdVeXFaV2N1czJDeWtlWVgrM0ZJWDFEckFrCnpOSGErdFdoUEY0aVZPMU9uSFdz
            citpcVU1TjcyRjFFNjVyYm5oYW4yMVUKLS0tIEUwOVB5R3FySzhJMFdyUGxvMUw0
            azA4eVdINVVjaXYvajNoVXFRRkdCRVUK/KU4iKEZf9zR0LYgUgFj2xviY0q2iBt9
            ytqAUbRmPA0/cO5qQEo/lUspa/S+96mp2qh27c1qGKf/N/qtJqbkLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T07:47:38Z"
    mac: ENC[AES256_GCM,data:lg06Ny1oEcmuB3AlTpWENc8n7r4hdrGVtoD7sYc5iCVsVcR/45ao6gDhAQI8Y2APrfDKJVlgWmkCVgTMRU63xaXHv+NX7z6gUo2oNv3Yuj5mhnwaHRsfx25V568uFWf9+s4pCvywjBNR/lPs155n728dwtIrox6v6nT2ElyCcIM=,iv:0HKoCqf9xi6euKaZBTM/OWTTv/kMwx/geO3NWcg9SwY=,tag:d1F+b2VEj1+qaALs6sllzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
