apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: karakeep-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - karakeep-secret.sops.yaml
