apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:BBwWIww=,iv:BbJXg5e0Y+aPFkytK8AImmfu6rvTSxn691rSo6/6c24=,tag:4SndGIXRagbg5hnwC0S7fQ==,type:str]
    admin-password: ENC[AES256_GCM,data:5QtvzbAIPqY=,iv:VxnvuX03g6ZDiB869L91AVGyKgt3gvmW8KNRD15GFPg=,tag:TP4gj4MpFsBS7Vs0oaL4Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUGh4T0J1WUNZS1ZjSzZ2
            NHplNHVyOXNuSVBrYzU3YTBsNXNCdm5CTWtVClhmYVR2OWlXY0JJM21kMGRnczhm
            eTNjTGpveDlmK0tjR0RBQjMxVG9NcDQKLS0tIEdkbHpqYyt2VWc4OUdQYkNoVVdp
            NkJPYWtPSlJmeC9OWkt4WS9zYlFwb0EKY/QoDGSnwF61W2A9dQq9++CrlPlrReSh
            JmCgEYKTVOrn38l+MvJDFZqYcdb1QkKB16yXlX+fqPulexiFVW7HCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T00:09:37Z"
    mac: ENC[AES256_GCM,data:1WqR6UaXapGRHqGd4OKI9MK+CvjrFgRIRfhWmpCJLTEVritvybRZCwwtqcw2OpR3ilsZaOD0gNqSKF6mmF8rmiXDhRcLdWi1QNcXN4BlrA5RVLoJOTCKHEACLHj/CSF1qrRDSNflEtpBPVud/p/Fh8X3nQ9tY3mX6lGFadDeLgM=,iv:koh0vefWaH+j9Fv6EMbqCQnzhI1vrqea+AMTLFxZMBU=,tag:Hz5WVL2KWlYZWGr4HlefOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
