apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:BQo0tA8=,iv:V8g7g+31nEocXw3cSqUvioXBZ8gomMlkcUn7BiEf0Vw=,tag:Rx2hgHTWaAYnTOQhKNxd/A==,type:str]
    admin-password: ENC[AES256_GCM,data:Bq9jnSOvr+s=,iv:+48C2c4zuzHLvpkLnCYiDABrqaQL8XF7x9Ij5N1lQPI=,tag:yT9ifVX0JT0wjAEVTPOeSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YjZCQnYzN2FkSzBTK0FM
            VnFUZEE4MnNDQ3hwRnQrSzBiWG9uaitBT1RBCm92TTdGcEtuZ0RVYVBnS3Z4UWg5
            TTVBakt3V3ZMVkhjc05iYUUxRk9IQjgKLS0tIFRGZXJIVWd5eXJrYnNkSVkvQkJk
            alVpQXEvcVd5OXI5YUJIQWhpellRaHcKf+hkF7CFtWVzL1lLBz1XMxPCoL26U3a9
            ese4zpi2ZTSR9rL5oW/1c2joWczq2Utd+Xoy7TP3sqOMnnk0Vztxkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T19:44:42Z"
    mac: ENC[AES256_GCM,data:2jY1+agAK2BzZozPG4odH16QtfIC2IbZJy4+FHGqxEd5/VpuwRki5d+miXZ67OzejFjE1RcuiUo6tsM9DYNKoFrvaYJnYWjORcYMFIpoEOc+gf8i4HiIVzC3Qp5Pahr7nba1s3A9wgSLgYXlOAO/WahaVu4Acm5gX0qVqvP9vs8=,iv:BDInmd4Huyf6J46r4DeuWCRdwIY1Uv2C/pI0iwUGq4c=,tag:MkOZS69ozsPEAHCJTzRCww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
