apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-cluster-overview.yaml
  - servicemonitor-cert-manager.yaml
  - servicemonitor-longhorn.yaml
  - nut-exporter.yaml

generators:
  - ksops-generator.yaml
