apiVersion: v1
kind: Secret
metadata:
    name: nut-secrets
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:t5YLJ9Le,iv:kqgmXofrmTPLkPqGrMIQSii/l80Sn5CF8pr9DwTCldg=,tag:OaSdVtOsyTkd+M9C4KT7vA==,type:str]
    password: ENC[AES256_GCM,data:lB3tvncXjkU=,iv:VXH6Ix5g76oyHAWyiZGU/sPbm/HHVPFZvm1loz3IqP8=,tag:dd8L3uf9HS0JkS9Zst+I7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK0k5OUgzUUE1dmtsM3dX
            R3p4Umw1NnR0NnhPT0txcU1jejY4UURJQ1dNCkR1NVpyUnJ4Yms3dWkrVEh2SEI0
            TW9zRWkvejhITFlRMDVHelJzK1BhWHcKLS0tIHdXQ3lVc0Y0M3YrN2FBZWoxQi9K
            RHlUMmRzWDhHeis3dE5lRStWMU5iSnMKdZELIc3PdP5HZxVS3J0cWaVv8I6pKKMD
            Huq4a6yTzaqHasi4Gyx8fgsahg+Lxkf176ZwnyRuxCZE6N9oPuMLfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T11:40:01Z"
    mac: ENC[AES256_GCM,data:SL2Yo4M0lHjV0HogUV4VTVge1yT/Q041095Tt9m0fgMY0emqoUFllnimTZvlnbghgSsA1ZzerXs3/uBVo8022m5zrbDIn+5f7WBxqLiT2JOniF0oVeZi+Aiqg//sbxlHUpnyp9tKJs4hChJ/Jk2zSxYoq7HIWgxVSuihz6hAOL0=,iv:a3PwAYrC2dV9MGo2e/eteDqlcjB5lLagqIw/2yTofkQ=,tag:P7dPn9bC2jpNQDCe7c2CDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
