apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:2zrVFh/raE1pTY9M3d1RwmVdtM1MOZKlcp2Jwo6ofb0q4pLgTEueAkYyQEEB6THrujr4vliARYdEKLQ64bhsdQ==,iv:N2/eVVr6thymKgkEWWJ3XdiTe57X8/G87v+dbrJR0qU=,tag:zPnEJSupDTgDcJxkg4IUOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUjBRSnI4aWdUNVgycGUz
            SXVndXdnVXdnN2c0ZXY1dWQvQzdmdDFtYmc0Ck9iNTJOUnVqZVNwRnhWOHVYa3l6
            czV3MG5PckhKY0VXRXp3ekJPVnNHWXcKLS0tIElVaVc2RWVOZk5UMS85RGdKaDFy
            NkFDZ0o0a1E5eXJJRW5jc1ZmR3JBa2sKBSl9vlFxJ9gel7pS8c7uy33yQMKVdEOS
            LMZNNCHW8nuxFxjOaxJcyN4mAQ0Zq39A1SvJMXawXOo0YiM2ENAd6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:31:14Z"
    mac: ENC[AES256_GCM,data:cANKv+jMgZFc3D+tewCbIOsh8NVzC5Yaz8hv8kNx8aGneKiIIpT1nP3gCTqSvLuwyR8V6QhLePmhy8+csouCuf+MrbypDSofMzK7fPK9nVlTX4X8t1obWVaXTUv61UmafsrcqxCakrEvgHNAJZJZPdo9/t1g1uQtagaVBMPedpY=,iv:pYiEn9Va+2d4qwxC4cndsYvbWV3yACWOKuEGN1v4SyU=,tag:cJpjYh8ppbE874fVVsyyWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
