apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:CXUCOP2HtFRVa+bWJYE7KmB+558YIXqKwbtgqFZw9y0uWmegiVzUzRmeNatO/4k1Pw2dai1kVnV+,iv:FIUvhPlaHiR9V5CeAQzk02r78rPUpybPSpgDHuUPHsE=,tag:fLfpbLqPouoA1wNkUFiBYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArazdkcUgxTHhXaWc3ZzlB
            VFpnUjV3bHhMMmxkRmxwRDVDK1dWNGc5VXlvClh6ckorWFliWC9QbXYzSTlHZmRJ
            Q0lsaFJwV2w5KzNNaGNtOGdnVytZMTgKLS0tIFlDQWdZelljdUVaT2ZSY2lsWGZJ
            dFF2YitRS2wybEtXV21tak52RzZiMVUK0k3Ykf6WnSRkOiclA+CNb5L4o8YjDjUn
            I56G6c23sWIOItrIrosDjwnAbnFnaDZ635Ug1mgFldYlTERJCHXQig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:00:14Z"
    mac: ENC[AES256_GCM,data:c7HMk0Jnbxd1K8bsDWqE5dFto4rPutM5dF0XOazHbNBbwr1CXwcfOlHEb7sRkNr+HNJyiD4086Pdi/S3d7HhxF4rR4+XEbrU4PYyDJmSo3Erd6sAc3+gw0uKp4J5eBpX79jC0JsCjnv0u1iHKWl6PPQdg3le90nAsNnunKmGoUQ=,iv:m7iCmHMwuBkT7Xza/ckfwL2nyJ7UckkRQ+vFsdnBg1Q=,tag:/kjqdLPDmwjuzbzhXPYQYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
