apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-data
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: garage-local
  local:
    path: /var/lib/garage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "temp-worker-node-migration"
