apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: garage-local
  volumeName: garage-data
  resources:
    requests:
      storage: 200Gi
