endpoints:
  - name: pve1
    group: homelab
    url: icmp://192.168.10.11
    interval: 10s
    conditions:
      - "[CONNECTED] == true"

  - name: pve2
    group: homelab
    url: icmp://192.168.10.12
    interval: 10s
    conditions:
      - "[CONNECTED] == true"

  - name: pve3
    group: homelab
    url: icmp://192.168.10.13
    interval: 10s
    conditions:
      - "[CONNECTED] == true"

  - name: ups-nut
    group: homelab
    # pve2 — NUT server moved here from pve3 around 2026-08-31
    url: tcp://192.168.10.12:3493
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
