endpoints:
  - name: pve1
    group: homelab
    url: icmp://192.168.10.10
    interval: 10s
    conditions:
      - "[CONNECTED] == true"

  - name: pve3
    group: homelab
    url: icmp://192.168.10.30
    interval: 10s
    conditions:
      - "[CONNECTED] == true"

  - name: 3145
    group: homelab
    url: icmp://192.168.20.10
    interval: 10s
    conditions:
      - "[CONNECTED] == true"

  - name: ups-nut
    group: homelab
    url: tcp://192.168.10.30:3493
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
