apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Xo1yN1Aoy2MuJMyS49RddoCDDFhhUd7sX5AXd3Uvq1jPqIlOXP06ebjTy1M26RX088EwMMvo/NcvU963pvr5iw==,iv:kVrFx/6CJ5GOj6BTiq6IkxuRTFpvvjlAa0nvymbKpa0=,tag:VDYBalsEblZ+T4N/UwY5aQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:ZT3mUnN7CPCEDYE88LBkW1d4cBRHAnZ2kRmEwskQl8k=,iv:o7peyqb3DDf6vuuver8iawsAVolWOGysFa753X9KTxo=,tag:Z+PrvLs3b3APKrc1bzO9eQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:Vs//qXtcIHI59V/Mh9Ptaa5TvJpdNwIV3BaESMGl5MA=,iv:Jq3dXmk+rPq+m1hsHme7OU6+L3OTvaDDN3FhUb2dHsc=,tag:Ti9Ei3i+NNKxLYRlIJEQUg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:o54bAyab1vmZHb9IX1qYCe0d/t7MqmjYtFT5jw==,iv:MYcEFNJSkkpi6O7f0gZLl2vGO2pTr7L3BrGeSZLCtkU=,tag:tUkuFG5/qRGGjj6ChXxaYQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:CWmL10AmlgMIKMUtEv4fxboTGOWu6af3BSE7gK3RzEB0UXEApfterz43Rsied8gcwWRGF3JPzgl83s++AacqQw==,iv:7l/lgImwKbVZcZFd2HUYXjeCnkSZeUPVUF/4aeiRlP0=,tag:2EUqNIIFtp/tD1+a2MGJHA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:4eaB/itfWPNdR3m6ieXUpqG0cYVEWB4=,iv:AZI3HetfxgrJFIJowW2/Kydu1OdMq6URNSFUxFhGvw4=,tag:qi1ZDi+dPB4aBv4knFVOPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU0M4cGNvMFA1UlgyUEJD
            bnpTbzhIREFqaEVMLzR6MVMraGQva3B5Y0RFCjN4VFJDZ0tJcHd0d1A2dUwrUkU4
            YmpPdXoza2d4RDh5UDlkNUFMZGpHcUUKLS0tIFFVK2RPLzEydW4zbXNzeHd0VmZs
            TUJHSEZ2a082Z1JoTThiY1JpUm5qNzgKVaIfohOgfBm9GpwRGYKUOLuei6t1vG+y
            4f6gHktQUZIktwjCySbpsmRJ3qlBuYnytrlxNk/4w1sNofiIqOeIVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T08:49:37Z"
    mac: ENC[AES256_GCM,data:OdAQgcjE71uZMrAJyleM59DrvFjYrZy9vHPixaFBQs9CsIydQsg6vcWP5EqiHf8PWzJY6j/R46pnT3WDiPzON4gRLyGc3ZJksmCR8zjpGAZrzBGdtsyVSvJcDpG5rCRQeCFyX8TvIbRbrOnsjK8MI+i/wmVsBmSMeXtYNCLnnLw=,iv:a1/8TB/nALCPrXPbgy16iogd8rKpIJH9OkTD9PbZfbM=,tag:mtRpnBpmAuHdDlb/opK0SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
