apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    ce180050-7bb3-47bf-a4dd-a4ec5e56d592.json: ENC[AES256_GCM,data:evs98w6v4WNdtAABzzJH2zxL2t502j/g97p4Ie9cPhKy7e/Kch8D03vcZpOU9BNTbRIbstdbFZFMxSyCJi4abnGfJiZdAZ/Jl7evuqp8lxpht2bPahK3PxHo+qaRDF+nRtl8qzuCQCbo+FYlbgXpyJ7v17z8gebvNxhkW0VZb+nRQu7rPszkJj4JS6LHAhsHzoK/B4yQ30IMNb6iIC6QluOnpC0s+g==,iv:0PnDZZH4xoCeoOWJHCWRYQ4hpMYZAbwMkXhYHg1siso=,tag:72HaSd3qNshDcbNl6vYOEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYWx4SmlwVjFUcStNQ1RG
            U1p3d0tIN2Eyb2xuVUdjQzI2VDNseE5ROXpRCkNtNVNaakEraGNaTzhBdGk0Z1dv
            QTRwY016SVAyN2ttbVNsTEs0L095ODQKLS0tIE9qb3JZWHNxTU1zVVhPaTlDM3kv
            b05aMkx6R0x2TzI0cDJySk43Ymt6WUUKpZ38U9ahLfEkdNsJEP8X1RimCAOcawuc
            Yt3c8nBvV4bVn4I8hn6GEIiE2hnb7c4mJHgGu+Pu+lGn6riIDIOV7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T10:13:24Z"
    mac: ENC[AES256_GCM,data:PynITa7RYxhMJrHBVZNX7vr7BMdMl8pmAn6PxWCY3aYXUPbsdoOBCHPxHl4LcssLXK/ueDDSTz8Gh/tG0+N5ZMZ8ETRh7d8T3VRz3nPTHlHI09cDiGzbamj3K6iSq/krLiDNNpYzlbP2oOAZa8FqsVK0TwqA/UgE4dIIBl5xDzk=,iv:ZqPhhujl6bTIu6Kdx88TBdrt7Ye+eNYCeGradG2QZuY=,tag:ATSPtyrfe6uDiqcPysGk9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
