apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:fnKlNR/XXKWxd4AG7xxQycbdkFkhyEk2f/AOoZps+FHvQjPqEkefhGvb+0lO64F6dxOl0x7avcE3sUeBpnRLRREqk/fTN8fJbzR6bfTPqwV4IbzP9tGPODQDkiCNzMi0etnEoouXawuok2PDUfcebBHJnV+F3eCBjppv6sAaugsSRRS/OXyWSvTV5InbaMwmY7EmZYVmrHSFWHcwSUjvXqoMAxfp0JnsnrQNj9AOFcZTQjtvr2MK3Q==,iv:MW1nLliKOnub0RT3EXCf0wFV1gYKqElizJGdphoOy2U=,tag:0/4df9KM8GTMi34PoayY0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdDA2OW1yZGwzd24vR0Mx
            WCt0c0dSNTVCcTdaZ2swVlRhUFdOZXRFVjBvCmxGWm9WaWlXdWo4Z3BlekpHdDRj
            VkJKeEducm9SN0pGblF1QU5sR2N1TUEKLS0tIHk5VEFBeWJGTWhlb1N5S3VUaHc4
            aUV3bStBQkpWbnh1YndDaVZZZUdkdlUKAWE5Ht6/HbsNj/dqCcHOucbv1QL6FfS7
            xTtbUS/DFvBFxup6ixujs4zcm7kzZZTQur9Hv+CpM8HWv+GD8733Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:26:28Z"
    mac: ENC[AES256_GCM,data:bNvWAngTNzAlqXgm7rfpW12nKXC+ZP62yUCF+g9fyVDR+dQPmU9wz1k1Xv+urcyXsl5CAepydRf/X4cRSAX+AuRxK5O7wI9p7K4kSLyGBZDd8kjdG+bBcDGkO3YkTxH3QdFePapW3u5mLd4A16fhLzsMyuYL8Qs8qKGfxonZcgs=,iv:qbdwfhKW/kzbIEOnmLWQ8STv1Fa74IAsEXrs3CBM+nY=,tag:/z5W1ZAceaJ4L0+ONAaivg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
