apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflared-tunnel-token-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cloudflared-tunnel-token.sops.yaml
  - cloudflared-credentials.sops.yaml
