apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
type: Opaque
stringData:
  tunnel-token: eyJhIjoiNDZmODM0ZDMxYTUxNTdiODE5ZmY5Yzg3OWVlMDc4NTEiLCJ0IjoiZGNlN2Y1ZmMtZDlkYS00OGIwLThjNjItNDA2MWU4ZTgyYmU2IiwicyI6IlpHRTJabUUwWXpFdE16Z3laUzAwTVRjNUxXRXlOamd0T1Rnd1lXSXdZbVUwWmpNMCJ9
